### ISSUE TITLE
Translation Request!

### ISSUE THREAD

**Issue by MrYKaushiK** [jahirfiquitiva/IconShowcase-Dashboard#18]
Hello,

I am Updated Hindi Translation in Language section please Update it in App language string file also update language Translation contribution!

Regards,
Yogesh KaushiK

**Comment by jahirfiquitiva** [comment]
Hi

IconShowcase is not maintained right now.
I'm working on a completely new version so I'm focusing on that instead of working on the old one.

Please kindly wait until the release of the new version since this is just a minor thing that doesn't affect performance or stability.

Also, please don't create issues in both repositories.

You can join the [Google+ Community](https://plus.google.com/communities/117748118619432374563) to stay tuned about next update.

Thanks.
