### ISSUE TITLE
Not auto-applying

### ISSUE THREAD

**Issue by alexcirco** [jahirfiquitiva/IconShowcase-Dashboard#19]
It's been 2 weeks now. I believe i did everything as should, all working great but the icons doesn't apply automatically (tried with nova and solo, both from launcher settings and Dashboard)

Configured: 
**xml>_appfilter, appmap, drawable, theme_resources_**
**values>icon pack>values>_icon_pack.xml_**

And copied: **_appfilter, drawable, theme_resources_** in **assets** as well

Also redownloaded the dashboard with no changes just used one icon and added it in the files mentioned above.

What could i be doing wrong? I'm dying here, please help me (newbie here)

**Comment by jahirfiquitiva** [comment]
Hello
Unfortunately I cannot provide help on this topic as it is not a dashboard issue

1. I'm not sure what you mean with "automatically" but if you expect icons to be applied right after app installation, like completely by itself, that's not going to happen.
2. Use the apply section from inside the app. If that does not work, then try going to your launcher settings and manually applying the icon pack. If that still does not work, then the issue is absolutely yours and has to do with the files you listed previously.

For further help, you can check [these links](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/wiki/How-to-create-an-Icon-Pack) and I am sure you will sort this out.

Good luck

**Comment by alexcirco** [comment]
This isn't helping man...i'm trying to apply them obviously i just wanted to ask where should i look into.

Ofc is my problem, followed exactly the tutorial, all files structures are written like they're supposed. I don't get what's wrong but thanks anyway...i'll just drop this whole thing. Also sorry but i didn't know where should I ask for help. Cheers and good luck at University^^

**Comment by jahirfiquitiva** [comment]
@alexcirco  You can ask in the [Google+ community](https://plus.google.com/communities/117748118619432374563) ... I'm sure other icon pack creators could help
