### ISSUE TITLE
home_configuration.xml

### ISSUE THREAD

**Issue by Luismi74** [jahirfiquitiva/IconShowcase-Dashboard#7]
bro cant find that file where is it?

**Comment by Luismi74** [comment]
hablo español por si acaso, hago un icon pack

**Comment by jahirfiquitiva** [comment]
@Luismi74 

1. Issues on GitHub must be in English.
2. Please don't refer to me as bro.
3. The current wiki is out-of-date because it will re-written for version 2.0 ... The current wiki corresponds to version [1.9.6.1](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/releases/tag/1.9.6.1). ... If you want to use the latest versions of IconShowcase, you might want to look to [this guide](https://github.com/jahirfiquitiva/IconShowcase-Dashboard/wiki/Updating-to-version-1.9.7.*), although it is supposed to be for people updating from 1.9.6.* versions, and I really don't have the time right now to update the wiki for new people.
This means you gotta mix the explanations from wiki and the ones for version 1.9.7.* and configure the dashboard accordingly.
4. The GitHub issues are expected to be real issues, not questions. If you have questions, please join the [community](https://plus.google.com/u/0/communities/117748118619432374563) and ask there.
5. To answer your question, `home_configuration.xml` does not exist anymore in the latest versions and has been merger into `dashboard_configuration.xml`

**Comment by Luismi74** [comment]
sorry, I didnt know there was a community, thanks for the answer
